apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`loadbalancer.peyton`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - name: web
    port: 80
    targetPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mc-server
  namespace: minecraft-server
spec:
  routes:
    - match: Host(`mc.peyton`)
      kind: Rule
      services:
        - name: minecraft-server
          kind: Service
          namespace: minecraft-server
          port: 25565