kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: traefik-test
  labels:
    app: whoami

spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: traefik-test

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: whoami

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test-app
  namespace: traefik-test
spec:
  routes:
    - match: Host(`local.traefik.test`)
      kind: Rule
      services:
        - name: whoami
          kind: Service
          namespace: traefik-test
          port: web


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: whoami-ingress
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /test/
#         pathType: Prefix
#         backend:
#           service:
#             name: whoami
#             namespace: traefik-test
#             port:
#               name: web
